spring:
  application:
    name: searchAndDestroyMS

  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://localhost:3306/product_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081